{
  access: {},
  tickData: [
    {
      stop: 0,
      target: 0,
      shift: 0,
      open: 3539,
      low: 3532,
      high: 3539,
      close: 3533,
      tickType: 'red',
      tickLength: 7,
      date: '',
      detecting: false,
      tradeStatus: 'not started',
      trend: '',
      time: '62614',
      x: 1
    },
    {
      stop: 0,
      target: 0,
      shift: 0,
      open: 3533,
      low: 3529,
      high: 3537,
      close: 3531,
      tickType: 'red',
      tickLength: 8,
      date: '',
      detecting: false,
      tradeStatus: 'not started',
      y: 3529,
      time: '63114',
      x: 2,
      direction: 'down'
    },
    {
      stop: 0,
      target: 0,
      shift: 0,
      open: 3531,
      low: 3531,
      high: 3539,
      close: 3538,
      tickType: 'green',
      tickLength: 8,
      date: '',
      detecting: false,
      tradeStatus: 'not started',
      y: 3539,
      time: '63614',
      x: 3,
      direction: 'up'
    },
    {
      stop: 0,
      target: 0,
      shift: 0,
      open: 3539,
      low: 3537,
      high: 3540,
      close: 3538,
      tickType: 'red',
      tickLength: 3,
      date: '',
      detecting: false,
      tradeStatus: 'not started',
      y: 3540,
      time: '64114',
      x: 4,
      direction: 'up'
    },
    {
      stop: 0,
      target: 0,
      shift: 0,
      open: 3538,
      low: 3538,
      high: 3545,
      close: 3541,
      tickType: 'green',
      tickLength: 7,
      date: '',
      detecting: false,
      tradeStatus: 'not started',
      y: 3545,
      time: '64614',
      x: 5,
      direction: 'up'
    },
    {
      stop: 0,
      target: 0,
      shift: 0,
      open: 3542,
      low: 3539,
      high: 3547,
      close: 3544,
      tickType: 'green',
      tickLength: 8,
      date: '',
      detecting: false,
      tradeStatus: 'not started',
      y: 3547,
      time: '7614',
      x: 6,
      direction: 'up'
    },
    {
      stop: 0,
      target: 0,
      shift: 0,
      open: 3544,
      low: 3543,
      high: 3549,
      close: 3549,
      tickType: 'green',
      tickLength: 6,
      date: '',
      detecting: false,
      tradeStatus: 'not started',
      y: 3549,
      time: '71114',
      x: 7,
      direction: 'up'
    },
    {
      stop: 0,
      target: 0,
      shift: 0,
      open: 3547,
      low: 3546,
      high: 3552,
      close: 3552,
      tickType: 'green',
      tickLength: 6,
      date: '',
      detecting: false,
      tradeStatus: 'not started',
      y: 3552,
      time: '75114',
      x: 8,
      direction: 'up'
    },
    {
      stop: 0,
      target: 0,
      shift: 0,
      open: 3544,
      low: 3542,
      high: 3551,
      close: 3546,
      tickType: 'green',
      tickLength: 9,
      date: '',
      detecting: false,
      tradeStatus: 'not started',
      y: 3542,
      time: '8614',
      x: 9,
      direction: 'down'
    },
    {
      stop: 0,
      target: 0,
      shift: 0,
      open: 3546,
      low: 3541,
      high: 3548,
      close: 3542,
      tickType: 'red',
      tickLength: 7,
      date: '',
      detecting: false,
      tradeStatus: 'not started',
      y: 3541,
      trend: 'downtrend',
      pivot: 3552,
      dir: 'up',
      currentPrice: 3542,
      time: '81114',
      x: 10,
      direction: 'down'
    },
    {
      stop: 0,
      target: 0,
      shift: 0,
      open: 3543,
      low: 3536,
      high: 3543,
      close: 3537,
      tickType: 'red',
      tickLength: 7,
      date: '',
      detecting: false,
      tradeStatus: 'not started',
      y: 3536,
      time: '82614',
      x: 11,
      direction: 'down'
    },
    {
      stop: 0,
      target: 0,
      shift: 0,
      open: 3537,
      low: 3526,
      high: 3541,
      close: 3535,
      tickType: 'red',
      tickLength: 15,
      date: '',
      detecting: false,
      tradeStatus: 'not started',
      y: 3526,
      time: '83114',
      x: 12,
      direction: 'down'
    },
    {
      stop: 0,
      target: 0,
      shift: 0,
      open: 3532,
      low: 3487,
      high: 3533,
      close: 3487,
      tickType: 'red',
      tickLength: 46,
      date: '',
      detecting: false,
      tradeStatus: 'not started',
      y: 3487,
      time: '84114',
      x: 13,
      direction: 'down'
    },
    {
      stop: 0,
      target: 0,
      shift: 0,
      open: 3487,
      low: 3470,
      high: 3488,
      close: 3482,
      tickType: 'red',
      tickLength: 18,
      date: '',
      detecting: false,
      tradeStatus: 'not started',
      y: 3470,
      time: '84614',
      x: 14,
      direction: 'down'
    },
    {
      stop: 0,
      target: 0,
      shift: 0,
      open: 3483,
      low: 3478,
      high: 3490,
      close: 3485,
      tickType: 'green',
      tickLength: 12,
      date: '',
      detecting: false,
      tradeStatus: 'not started',
      y: 3490,
      time: '85114',
      x: 15,
      direction: 'up'
    },
    {
      stop: 0,
      target: 0,
      shift: 0,
      open: 3486,
      low: 3486,
      high: 3493,
      close: 3489,
      tickType: 'green',
      tickLength: 7,
      date: '',
      detecting: false,
      tradeStatus: 'not started',
      y: 3493,
      trend: 'upward',
      pivot: 3470,
      dir: 'low',
      currentPrice: 3489,
      time: '85614',
      x: 16,
      direction: 'up'
    },
    {
      stop: 0,
      target: 0,
      shift: 0,
      open: 3492,
      low: 3482,
      high: 3496,
      close: 3490,
      tickType: 'red',
      tickLength: 14,
      date: '',
      detecting: false,
      tradeStatus: 'not started',
      y: 3496,
      time: '9614',
      x: 17,
      direction: 'up'
    },
    {
      stop: 0,
      target: 0,
      shift: 0,
      open: 3490,
      low: 3489,
      high: 3497,
      close: 3496,
      tickType: 'green',
      tickLength: 8,
      date: '',
      detecting: false,
      tradeStatus: 'not started',
      y: 3497,
      time: '91114',
      x: 18,
      direction: 'up'
    },
    {
      stop: 0,
      target: 0,
      shift: 0,
      open: 3496,
      low: 3479,
      high: 3496,
      close: 3484,
      tickType: 'red',
      tickLength: 17,
      date: '',
      detecting: false,
      tradeStatus: 'not started',
      y: 3479,
      time: '91614',
      x: 19,
      direction: 'down'
    },
    {
      stop: 0,
      target: 0,
      shift: 0,
      open: 3484,
      low: 3475,
      high: 3485,
      close: 3476,
      tickType: 'red',
      tickLength: 10,
      date: '',
      detecting: false,
      tradeStatus: 'not started',
      y: 3475,
      trend: 'downtrend',
      pivot: 3497,
      dir: 'up',
      currentPrice: 3476,
      time: '92114',
      x: 20,
      direction: 'down'
    },
    {
      stop: 0,
      target: 0,
      shift: 0,
      open: 3475,
      low: 3473,
      high: 3482,
      close: 3479,
      tickType: 'green',
      tickLength: 9,
      date: '',
      detecting: false,
      tradeStatus: 'not started',
      y: 3473,
      time: '92614',
      x: 21,
      direction: 'down'
    },
    {
      stop: 0,
      target: 0,
      shift: 0,
      open: 3479,
      low: 3475,
      high: 3484,
      close: 3475,
      tickType: 'red',
      tickLength: 9,
      date: '',
      detecting: false,
      tradeStatus: 'not started',
      y: 3484,
      time: '93114',
      x: 22,
      direction: 'up'
    },
    {
      stop: 0,
      target: 0,
      shift: 0,
      open: 3481,
      low: 3478,
      high: 3493,
      close: 3492,
      tickType: 'green',
      tickLength: 15,
      date: '',
      detecting: false,
      tradeStatus: 'not started',
      y: 3493,
      trend: 'upward',
      pivot: 3473,
      dir: 'low',
      currentPrice: 3492,
      time: '94114',
      x: 23,
      direction: 'up'
    },
    {
      stop: 0,
      target: 0,
      shift: 0,
      open: 3493,
      low: 3491,
      high: 3495,
      close: 3494,
      tickType: 'green',
      tickLength: 4,
      date: '',
      detecting: false,
      tradeStatus: 'not started',
      y: 3495,
      time: '94614',
      x: 24,
      direction: 'up'
    },
    {
      stop: 0,
      target: 0,
      shift: 0,
      open: 3494,
      low: 3492,
      high: 3496,
      close: 3494,
      tickType: 'doji',
      tickLength: 4,
      date: '',
      detecting: false,
      tradeStatus: 'not started',
      y: 3496,
      time: '95114',
      x: 25,
      direction: 'up'
    },
    {
      stop: 0,
      target: 0,
      shift: 0,
      open: 3493,
      low: 3486,
      high: 3497,
      close: 3489,
      tickType: 'red',
      tickLength: 11,
      date: '',
      detecting: false,
      tradeStatus: 'not started',
      y: 3497,
      time: '95614',
      x: 26,
      direction: 'up'
    },
    {
      stop: 0,
      target: 0,
      shift: 0,
      open: 3491,
      low: 3489,
      high: 3500,
      close: 3499,
      tickType: 'green',
      tickLength: 11,
      date: '',
      detecting: false,
      tradeStatus: 'not started',
      y: 3500,
      time: '102114',
      x: 27,
      direction: 'up'
    },
    {
      stop: 0,
      target: 0,
      shift: 0,
      open: 3499,
      low: 3495,
      high: 3502,
      close: 3495,
      tickType: 'red',
      tickLength: 7,
      date: '',
      detecting: false,
      tradeStatus: 'not started',
      y: 3502,
      time: '102614',
      x: 28,
      direction: 'up'
    },
    {
      stop: 0,
      target: 0,
      shift: 0,
      open: 3495,
      low: 3493,
      high: 3498,
      close: 3494,
      tickType: 'red',
      tickLength: 5,
      date: '',
      detecting: false,
      tradeStatus: 'not started',
      y: 3493,
      time: '103114',
      x: 29,
      direction: 'down'
    },
    {
      stop: 0,
      target: 0,
      shift: 0,
      open: 3497,
      low: 3492,
      high: 3497,
      close: 3492,
      tickType: 'red',
      tickLength: 5,
      date: '',
      detecting: false,
      tradeStatus: 'not started',
      y: 3492,
      trend: 'downtrend',
      pivot: 3502,
      dir: 'up',
      currentPrice: 3492,
      time: '104114',
      x: 30,
      direction: 'down'
    },
    {
      stop: 0,
      target: 0,
      shift: 0,
      open: 3491,
      low: 3491,
      high: 3498,
      close: 3496,
      tickType: 'green',
      tickLength: 7,
      date: '',
      detecting: false,
      tradeStatus: 'not started',
      y: 3498,
      time: '104614',
      x: 31,
      direction: 'up'
    },
    {
      stop: 0,
      target: 0,
      shift: 0,
      open: 3496,
      low: 3492,
      high: 3503,
      close: 3498,
      tickType: 'green',
      tickLength: 11,
      date: '',
      detecting: false,
      tradeStatus: 'not started',
      y: 3503,
      trend: 'upward',
      pivot: 3492,
      dir: 'low',
      currentPrice: 3498,
      time: '105614',
      x: 32,
      direction: 'up'
    },
    {
      stop: 0,
      target: 0,
      shift: 0,
      open: 3498,
      low: 3497,
      high: 3518,
      close: 3510,
      tickType: 'green',
      tickLength: 21,
      date: '',
      detecting: false,
      tradeStatus: 'not started',
      y: 3518,
      time: '11114',
      x: 33,
      direction: 'up'
    },
    {
      stop: 0,
      target: 0,
      shift: 0,
      open: 3498,
      low: 3488,
      high: 3498,
      close: 3493,
      tickType: 'red',
      tickLength: 10,
      date: '',
      detecting: false,
      tradeStatus: 'not started',
      y: 3488,
      time: '112614',
      x: 34,
      direction: 'down'
    },
    {
      stop: 0,
      target: 0,
      shift: 0,
      open: 3493,
      low: 3486,
      high: 3494,
      close: 3489,
      tickType: 'red',
      tickLength: 8,
      date: '',
      detecting: false,
      tradeStatus: 'not started',
      y: 3486,
      trend: 'downtrend',
      pivot: 3518,
      dir: 'up',
      currentPrice: 3489,
      time: '113114',
      x: 35,
      direction: 'down'
    },
    {
      stop: 0,
      target: 0,
      shift: 0,
      open: 3491,
      low: 3491,
      high: 3498,
      close: 3497,
      tickType: 'green',
      tickLength: 7,
      date: '',
      detecting: false,
      tradeStatus: 'not started',
      y: 3498,
      time: '114614',
      x: 36,
      direction: 'up'
    },
    {
      stop: 0,
      target: 0,
      shift: 0,
      open: 3497,
      low: 3496,
      high: 3501,
      close: 3501,
      tickType: 'green',
      tickLength: 5,
      date: '',
      detecting: false,
      tradeStatus: 'not started',
      y: 3501,
      trend: 'upward',
      pivot: 3486,
      dir: 'low',
      currentPrice: 3501,
      time: '115114',
      x: 37,
      direction: 'up'
    },
    {
      stop: 0,
      target: 0,
      shift: 0,
      open: 3500,
      low: 3492,
      high: 3502,
      close: 3499,
      tickType: 'red',
      tickLength: 10,
      date: '',
      detecting: false,
      tradeStatus: 'not started',
      y: 3502,
      time: '115614',
      x: 38,
      direction: 'up'
    },
    {
      stop: 0,
      target: 0,
      shift: 0,
      open: 3499,
      low: 3497,
      high: 3526,
      close: 3503,
      tickType: 'green',
      tickLength: 29,
      date: '',
      detecting: false,
      tradeStatus: 'not started',
      y: 3526,
      time: '12114',
      x: 39,
      direction: 'up'
    },
    {
      stop: 0,
      target: 0,
      shift: 0,
      open: 3516,
      low: 3512,
      high: 3532,
      close: 3528,
      tickType: 'green',
      tickLength: 20,
      date: '',
      detecting: false,
      tradeStatus: 'not started',
      y: 3532,
      time: '121114',
      x: 40,
      direction: 'up'
    },
    {
      stop: 0,
      target: 0,
      shift: 0,
      open: 3528,
      low: 3524,
      high: 3550,
      close: 3547,
      tickType: 'green',
      tickLength: 26,
      date: '',
      detecting: false,
      tradeStatus: 'not started',
      y: 3550,
      time: '121614',
      x: 41,
      direction: 'up'
    },
    {
      stop: 0,
      target: 0,
      shift: 0,
      open: 3548,
      low: 3545,
      high: 3575,
      close: 3575,
      tickType: 'green',
      tickLength: 30,
      date: '',
      detecting: false,
      tradeStatus: 'not started',
      y: 3575,
      time: '122114',
      x: 42,
      direction: 'up'
    },
    {
      stop: 0,
      target: 0,
      shift: 0,
      open: 3575,
      low: 3571,
      high: 3588,
      close: 3578,
      tickType: 'green',
      tickLength: 17,
      date: '',
      detecting: false,
      tradeStatus: 'not started',
      y: 3588,
      time: '122614',
      x: 43,
      direction: 'up'
    },
    {
      stop: 0,
      target: 0,
      shift: 0,
      open: 3580,
      low: 3565,
      high: 3583,
      close: 3571,
      tickType: 'red',
      tickLength: 18,
      date: '',
      detecting: false,
      tradeStatus: 'not started',
      y: 3565,
      time: '123614',
      x: 44,
      direction: 'down'
    },
    {
      stop: 0,
      target: 0,
      shift: 0,
      open: 3571,
      low: 3562,
      high: 3573,
      close: 3563,
      tickType: 'red',
      tickLength: 11,
      date: '',
      detecting: false,
      tradeStatus: 'not started',
      y: 3562,
      trend: 'downtrend',
      pivot: 3588,
      dir: 'up',
      currentPrice: 3563,
      time: '124114',
      x: 45,
      direction: 'down'
    },
    {
      stop: 0,
      target: 0,
      shift: 0,
      open: 3564,
      low: 3553,
      high: 3564,
      close: 3559,
      tickType: 'red',
      tickLength: 11,
      date: '',
      detecting: false,
      tradeStatus: 'not started',
      y: 3553,
      time: '124614',
      x: 46,
      direction: 'down'
    },
    {
      stop: 0,
      target: 0,
      shift: 0,
      open: 3559,
      low: 3558,
      high: 3572,
      close: 3568,
      tickType: 'green',
      tickLength: 14,
      date: '',
      detecting: false,
      tradeStatus: 'not started',
      y: 3572,
      time: '125115',
      x: 47,
      direction: 'up'
    },
    {
      stop: 0,
      target: 0,
      shift: 0,
      open: 3568,
      low: 3563,
      high: 3581,
      close: 3578,
      tickType: 'green',
      tickLength: 18,
      date: '',
      detecting: false,
      tradeStatus: 'not started',
      y: 3581,
      trend: 'upward',
      pivot: 3553,
      dir: 'low',
      currentPrice: 3578,
      time: '125615',
      x: 48,
      direction: 'up'
    },
    {
      stop: 0,
      target: 0,
      shift: 0,
      open: 3578,
      low: 3562,
      high: 3578,
      close: 3563,
      tickType: 'red',
      tickLength: 16,
      date: '',
      detecting: false,
      tradeStatus: 'not started',
      y: 3562,
      time: '13115',
      x: 49,
      direction: 'down'
    },
    {
      stop: 0,
      target: 0,
      shift: 0,
      open: 3562,
      low: 3560,
      high: 3568,
      close: 3560,
      tickType: 'red',
      tickLength: 8,
      date: '',
      detecting: false,
      tradeStatus: 'not started',
      y: 3560,
      trend: 'downtrend',
      pivot: 3581,
      dir: 'up',
      currentPrice: 3560,
      time: '13615',
      x: 50,
      direction: 'down'
    },
    {
      stop: 0,
      target: 0,
      shift: 0,
      open: 3561,
      low: 3561,
      high: 3572,
      close: 3569,
      tickType: 'green',
      tickLength: 11,
      date: '',
      detecting: false,
      tradeStatus: 'not started',
      y: 3572,
      time: '132115',
      x: 51,
      direction: 'up'
    },
    {
      stop: 0,
      target: 0,
      shift: 0,
      open: 3569,
      low: 3568,
      high: 3594,
      close: 3586,
      tickType: 'green',
      tickLength: 26,
      date: '',
      detecting: false,
      tradeStatus: 'not started',
      y: 3594,
      trend: 'upward',
      pivot: 3560,
      dir: 'low',
      currentPrice: 3586,
      time: '132615',
      x: 52,
      direction: 'up'
    },
    {
      stop: 0,
      target: 0,
      shift: 0,
      open: 3587,
      low: 3587,
      high: 3607,
      close: 3603,
      tickType: 'green',
      tickLength: 20,
      date: '',
      detecting: false,
      tradeStatus: 'not started',
      y: 3607,
      time: '134615',
      x: 53,
      direction: 'up'
    },
    {
      stop: 0,
      target: 0,
      shift: 0,
      open: 3594,
      low: 3578,
      high: 3595,
      close: 3581,
      tickType: 'red',
      tickLength: 17,
      date: '',
      detecting: false,
      tradeStatus: 'not started',
      y: 3578,
      time: '135615',
      x: 54,
      direction: 'down'
    },
    {
      stop: 0,
      target: 0,
      shift: 0,
      open: 3581,
      low: 3572,
      high: 3585,
      close: 3581,
      tickType: 'doji',
      tickLength: 13,
      date: '',
      detecting: false,
      tradeStatus: 'not started',
      y: 3572,
      trend: 'downtrend',
      pivot: 3607,
      dir: 'up',
      currentPrice: 3581,
      time: '14115',
      x: 55,
      direction: 'down'
    },
    {
      stop: 0,
      target: 0,
      shift: 0,
      open: 3581,
      low: 3566,
      high: 3581,
      close: 3581,
      tickType: 'doji',
      tickLength: 15,
      date: '',
      detecting: false,
      tradeStatus: 'not started',
      y: 3566,
      time: '14615',
      x: 56,
      direction: 'down'
    },
    {
      stop: 0,
      target: 0,
      shift: 0,
      open: 3580,
      low: 3578,
      high: 3585,
      close: 3584,
      tickType: 'green',
      tickLength: 7,
      date: '',
      detecting: false,
      tradeStatus: 'not started',
      y: 3585,
      time: '141115',
      x: 57,
      direction: 'up'
    },
    {
      stop: 0,
      target: 0,
      shift: 0,
      open: 3583,
      low: 3580,
      high: 3590,
      close: 3583,
      tickType: 'doji',
      tickLength: 10,
      date: '',
      detecting: false,
      tradeStatus: 'not started',
      y: 3590,
      trend: 'upward',
      pivot: 3566,
      dir: 'low',
      currentPrice: 3583,
      time: '141615',
      x: 58,
      direction: 'up'
    },
    {
      stop: 0,
      target: 0,
      shift: 0,
      open: 3583,
      low: 3580,
      high: 3596,
      close: 3594,
      tickType: 'green',
      tickLength: 16,
      date: '',
      detecting: false,
      tradeStatus: 'not started',
      y: 3596,
      time: '143115',
      x: 59,
      direction: 'up'
    },
    {
      stop: 0,
      target: 0,
      shift: 0,
      open: 3594,
      low: 3576,
      high: 3600,
      close: 3600,
      tickType: 'green',
      tickLength: 24,
      date: '',
      detecting: false,
      tradeStatus: 'not started',
      y: 3600,
      time: '143615',
      x: 60,
      direction: 'up'
    },
    {
      stop: 0,
      target: 0,
      shift: 0,
      open: 3601,
      low: 3593,
      high: 3612,
      close: 3597,
      tickType: 'red',
      tickLength: 19,
      date: '',
      detecting: false,
      tradeStatus: 'not started',
      y: 3612,
      time: '144115',
      x: 61,
      direction: 'up'
    },
    {
      stop: 0,
      target: 0,
      shift: 0,
      open: 3599,
      low: 3588,
      high: 3610,
      close: 3595,
      tickType: 'red',
      tickLength: 22,
      date: '',
      detecting: false,
      tradeStatus: 'not started',
      y: 3588,
      time: '145115',
      x: 62,
      direction: 'down'
    },
    {
      stop: 0,
      target: 0,
      shift: 0,
      open: 3599,
      low: 3581,
      high: 3599,
      close: 3584,
      tickType: 'red',
      tickLength: 18,
      date: '',
      detecting: false,
      tradeStatus: 'not started',
      y: 3581,
      trend: 'downtrend',
      pivot: 3612,
      dir: 'up',
      currentPrice: 3584,
      time: '15115',
      x: 63,
      direction: 'down'
    },
    {
      stop: 0,
      target: 0,
      shift: 0,
      open: 3591,
      low: 3580,
      high: 3591,
      close: 3588,
      tickType: 'red',
      tickLength: 11,
      date: '',
      detecting: false,
      tradeStatus: 'not started',
      y: 3580,
      time: '151115',
      x: 64,
      direction: 'down'
    },
    {
      stop: 0,
      target: 0,
      shift: 0,
      open: 3588,
      low: 3570,
      high: 3588,
      close: 3572,
      tickType: 'red',
      tickLength: 18,
      date: '',
      detecting: false,
      tradeStatus: 'not started',
      y: 3570,
      time: '151615',
      x: 65,
      direction: 'down'
    },
    {
      stop: 0,
      target: 0,
      shift: 0,
      open: 3573,
      low: 3564,
      high: 3575,
      close: 3574,
      tickType: 'green',
      tickLength: 11,
      date: '',
      detecting: false,
      tradeStatus: 'not started',
      y: 3564,
      time: '152115',
      x: 66,
      direction: 'down'
    },
    {
      stop: 0,
      target: 0,
      shift: 0,
      open: 3574,
      low: 3573,
      high: 3586,
      close: 3582,
      tickType: 'green',
      tickLength: 13,
      date: '',
      detecting: false,
      tradeStatus: 'not started',
      y: 3586,
      time: '152615',
      x: 67,
      direction: 'up'
    },
    {
      stop: 0,
      target: 0,
      shift: 0,
      open: 3582,
      low: 3574,
      high: 3595,
      close: 3587,
      tickType: 'green',
      tickLength: 21,
      date: '',
      detecting: false,
      tradeStatus: 'not started',
      y: 3595,
      trend: 'upward',
      pivot: 3564,
      dir: 'low',
      currentPrice: 3587,
      time: '153115',
      x: 68,
      direction: 'up'
    },
    {
      stop: 0,
      target: 0,
      shift: 0,
      open: 3587,
      low: 3580,
      high: 3597,
      close: 3591,
      tickType: 'green',
      tickLength: 17,
      date: '',
      detecting: false,
      tradeStatus: 'not started',
      y: 3597,
      time: '153615',
      x: 69,
      direction: 'up'
    },
    {
      stop: 0,
      target: 0,
      shift: 0,
      open: 3594,
      low: 3587,
      high: 3601,
      close: 3589,
      tickType: 'red',
      tickLength: 14,
      date: '',
      detecting: false,
      tradeStatus: 'not started',
      y: 3601,
      time: '155115',
      x: 70,
      direction: 'up'
    },
    {
      stop: 0,
      target: 0,
      shift: 0,
      open: 3589,
      low: 3589,
      high: 3606,
      close: 3598,
      tickType: 'green',
      tickLength: 17,
      date: '',
      detecting: false,
      tradeStatus: 'not started',
      y: 3606,
      time: '155615',
      x: 71,
      direction: 'up'
    },
    {
      stop: 0,
      target: 0,
      shift: 0,
      open: 3598,
      low: 3596,
      high: 3615,
      close: 3608,
      tickType: 'green',
      tickLength: 19,
      date: '',
      detecting: false,
      tradeStatus: 'not started',
      y: 3615,
      time: '16115',
      x: 72,
      direction: 'up'
    },
    {
      stop: 0,
      target: 0,
      shift: 0,
      open: 3608,
      low: 3602,
      high: 3620,
      close: 3614,
      tickType: 'green',
      tickLength: 18,
      date: '',
      detecting: false,
      tradeStatus: 'not started',
      y: 3620,
      time: '16615',
      x: 73,
      direction: 'up'
    },
    {
      stop: 0,
      target: 0,
      shift: 0,
      open: 3614,
      low: 3598,
      high: 3617,
      close: 3603,
      tickType: 'red',
      tickLength: 19,
      date: '',
      detecting: false,
      tradeStatus: 'not started',
      y: 3598,
      time: '161114',
      x: 74,
      direction: 'down'
    },
    {
      stop: 0,
      target: 0,
      shift: 0,
      open: 3610,
      low: 3592,
      high: 3612,
      close: 3594,
      tickType: 'red',
      tickLength: 20,
      date: '',
      detecting: false,
      tradeStatus: 'not started',
      y: 3592,
      trend: 'downtrend',
      pivot: 3620,
      dir: 'up',
      currentPrice: 3594,
      time: '162114',
      x: 75,
      direction: 'down'
    },
    {
      stop: 0,
      target: 0,
      shift: 0,
      open: 3600,
      low: 3600,
      high: 3613,
      close: 3608,
      tickType: 'green',
      tickLength: 13,
      date: '',
      detecting: false,
      tradeStatus: 'not started',
      y: 3613,
      time: '163114',
      x: 76,
      direction: 'up'
    },
    {
      stop: 0,
      target: 0,
      shift: 0,
      open: 3608,
      low: 3608,
      high: 3617,
      close: 3612,
      tickType: 'green',
      tickLength: 9,
      date: '',
      detecting: false,
      tradeStatus: 'not started',
      y: 3617,
      trend: 'upward',
      pivot: 3592,
      dir: 'low',
      currentPrice: 3612,
      time: '163614',
      x: 77,
      direction: 'up'
    },
    {
      stop: 0,
      target: 0,
      shift: 0,
      open: 3612,
      low: 3612,
      high: 3630,
      close: 3625,
      tickType: 'green',
      tickLength: 18,
      date: '',
      detecting: false,
      tradeStatus: 'not started',
      y: 3630,
      time: '164114',
      x: 78,
      direction: 'up'
    },
    {
      stop: 0,
      target: 0,
      shift: 0,
      open: 3623,
      low: 3623,
      high: 3638,
      close: 3632,
      tickType: 'green',
      tickLength: 15,
      date: '',
      detecting: false,
      tradeStatus: 'not started',
      y: 3638,
      time: '164614',
      x: 79,
      direction: 'up'
    },
    {
      stop: 0,
      target: 0,
      shift: 0,
      open: 3625,
      low: 3621,
      high: 3628,
      close: 3623,
      tickType: 'red',
      tickLength: 7,
      date: '',
      detecting: false,
      tradeStatus: 'not started',
      y: 3621,
      time: '165614',
      x: 80,
      direction: 'down'
    },
    {
      stop: 0,
      target: 0,
      shift: 0,
      open: 3623,
      low: 3618,
      high: 3624,
      close: 3618,
      tickType: 'red',
      tickLength: 6,
      date: '',
      detecting: false,
      tradeStatus: 'not started',
      y: 3618,
      trend: 'downtrend',
      pivot: 3638,
      dir: 'up',
      currentPrice: 3618,
      time: '17114',
      x: 81,
      direction: 'down'
    },
    {
      stop: 0,
      target: 0,
      shift: 0,
      open: 3616,
      low: 3613,
      high: 3617,
      close: 3615,
      tickType: 'red',
      tickLength: 4,
      date: '',
      detecting: false,
      tradeStatus: 'not started',
      y: 3613,
      time: '171614',
      x: 82,
      direction: 'down'
    }
  ],
  plData: [
    {
      x: 0,
      y: 3539
    },
    {
      x: 1,
      y: 3552,
      dir: 'up',
      date: '',
      currentPrice: 3542,
      tradeStatus: 'not started',
      crudeTradePrice: 0,
      crudeTradeManagement: false,
      lowest: 3539,
      highest: 3552,
      sidecount: 0
    },
    {
      x: 2,
      y: 3470,
      dir: 'low',
      date: '',
      currentPrice: 3489,
      tradeStatus: 'not started',
      crudeTradePrice: 0,
      crudeTradeManagement: false,
      highest: 3552,
      lowest: 3470,
      downcount: 0,
      sidecount: 0,
      upcount: 0,
      upblackextreme: 0,
      lowblackextreme: 0,
      UPblackpoint: 0,
      Lowblackpoint: 0
    },
    {
      x: 3,
      y: 3497,
      dir: 'up',
      date: '',
      currentPrice: 3476,
      tradeStatus: 'not started',
      crudeTradePrice: 0,
      crudeTradeManagement: false,
      upcount: 0,
      downcount: 0,
      highest: 3552,
      lowest: 3470,
      UPblackpoint: 0,
      Lowblackpoint: 0,
      lowblackextreme: 0,
      upblackextreme: 0,
      sidecount: 1
    },
    {
      x: 4,
      y: 3473,
      dir: 'low',
      date: '',
      currentPrice: 3492,
      tradeStatus: 'not started',
      crudeTradePrice: 0,
      crudeTradeManagement: false,
      upcount: 0,
      downcount: 0,
      highest: 3552,
      lowest: 3470,
      UPblackpoint: 0,
      Lowblackpoint: 0,
      lowblackextreme: 0,
      upblackextreme: 0,
      sidecount: 2
    },
    {
      x: 5,
      y: 3502,
      dir: 'up',
      date: '',
      currentPrice: 3492,
      tradeStatus: 'not started',
      crudeTradePrice: 0,
      crudeTradeManagement: false,
      upcount: 0,
      downcount: 0,
      highest: 3552,
      lowest: 3470,
      UPblackpoint: 0,
      Lowblackpoint: 0,
      lowblackextreme: 0,
      upblackextreme: 0,
      sidecount: 3
    },
    {
      x: 6,
      y: 3492,
      dir: 'low',
      date: '',
      currentPrice: 3498,
      tradeStatus: 'not started',
      crudeTradePrice: 0,
      crudeTradeManagement: false,
      upcount: 0,
      downcount: 0,
      highest: 3552,
      lowest: 3470,
      UPblackpoint: 0,
      Lowblackpoint: 0,
      lowblackextreme: 0,
      upblackextreme: 0,
      sidecount: 4,
      trend: 'sideways'
    },
    {
      x: 7,
      y: 3518,
      dir: 'up',
      date: '',
      currentPrice: 3489,
      tradeStatus: 'not started',
      crudeTradePrice: 0,
      crudeTradeManagement: false,
      upcount: 0,
      downcount: 0,
      highest: 3552,
      lowest: 3470,
      trend: 'sideways',
      UPblackpoint: 0,
      Lowblackpoint: 0,
      lowblackextreme: 0,
      upblackextreme: 0,
      sidecount: 5
    },
    {
      x: 8,
      y: 3486,
      dir: 'low',
      date: '',
      currentPrice: 3501,
      tradeStatus: 'not started',
      crudeTradePrice: 0,
      crudeTradeManagement: false,
      upcount: 0,
      downcount: 0,
      highest: 3552,
      lowest: 3470,
      trend: 'sideways',
      UPblackpoint: 0,
      Lowblackpoint: 0,
      lowblackextreme: 0,
      upblackextreme: 0,
      sidecount: 6
    },
    {
      x: 9,
      y: 3588,
      dir: 'up',
      date: '',
      currentPrice: 3563,
      tradeStatus: 'not started',
      crudeTradePrice: 0,
      crudeTradeManagement: false,
      upcount: 0,
      downcount: 0,
      highest: 3588,
      lowest: 3486,
      trend: 'sideways',
      UPblackpoint: 0,
      Lowblackpoint: 0,
      lowblackextreme: 0,
      upblackextreme: 0,
      bigDayTrade: 'short',
      bigDayTradePrice: 3588,
      sidecount: 0
    },
    {
      x: 10,
      y: 3553,
      dir: 'low',
      date: '',
      currentPrice: 3578,
      tradeStatus: 'not started',
      crudeTradePrice: 0,
      crudeTradeManagement: false,
      upcount: 0,
      downcount: 0,
      highest: 3588,
      lowest: 3486,
      trend: 'sideways',
      UPblackpoint: 0,
      Lowblackpoint: 0,
      lowblackextreme: 0,
      upblackextreme: 0,
      bigDayTrade: 'short',
      bigDayTradePrice: 3588,
      sidecount: 1
    },
    {
      x: 11,
      y: 3581,
      dir: 'up',
      date: '',
      currentPrice: 3560,
      tradeStatus: 'not started',
      crudeTradePrice: 0,
      crudeTradeManagement: false,
      upcount: 0,
      downcount: 0,
      highest: 3588,
      lowest: 3486,
      trend: 'sideways',
      UPblackpoint: 0,
      Lowblackpoint: 0,
      lowblackextreme: 0,
      upblackextreme: 0,
      bigDayTrade: 'short',
      bigDayTradePrice: 3588,
      sidecount: 2
    },
    {
      x: 12,
      y: 3560,
      dir: 'low',
      date: '',
      currentPrice: 3586,
      tradeStatus: 'not started',
      crudeTradePrice: 0,
      crudeTradeManagement: false,
      upcount: 0,
      downcount: 0,
      highest: 3588,
      lowest: 3486,
      trend: 'sideways',
      UPblackpoint: 0,
      Lowblackpoint: 0,
      lowblackextreme: 0,
      upblackextreme: 0,
      bigDayTrade: 'short',
      bigDayTradePrice: 3588,
      sidecount: 3
    },
    {
      x: 13,
      y: 3607,
      dir: 'up',
      date: '',
      currentPrice: 3581,
      tradeStatus: 'not started',
      crudeTradePrice: 0,
      crudeTradeManagement: false,
      upcount: 0,
      downcount: 0,
      highest: 3588,
      lowest: 3486,
      trend: 'sideways',
      UPblackpoint: 3607,
      Lowblackpoint: 0,
      lowblackextreme: 0,
      upblackextreme: 3607,
      bigDayTrade: 'short',
      bigDayTradePrice: 3588,
      UPblackpointindex: 13
    },
    {
      x: 14,
      y: 3566,
      dir: 'low',
      date: '',
      currentPrice: 3583,
      tradeStatus: 'not started',
      crudeTradePrice: 0,
      crudeTradeManagement: false,
      upcount: 0,
      downcount: 0,
      highest: 3588,
      lowest: 3486,
      trend: 'sideways',
      UPblackpoint: 3607,
      Lowblackpoint: 0,
      lowblackextreme: 0,
      upblackextreme: 3607,
      bigDayTrade: 'short',
      bigDayTradePrice: 3588,
      sidecount: null
    },
    {
      x: 15,
      y: 3612,
      dir: 'up',
      date: '',
      currentPrice: 3584,
      tradeStatus: 'not started',
      crudeTradePrice: 0,
      crudeTradeManagement: false,
      upcount: 0,
      downcount: 0,
      highest: 3588,
      lowest: 3486,
      trend: 'sideways',
      UPblackpoint: 3607,
      Lowblackpoint: 0,
      lowblackextreme: 0,
      upblackextreme: 3607,
      bigDayTrade: 'short',
      bigDayTradePrice: 3588,
      retesthappen: true,
      ShortTradeInitiated: true,
      TradeStarted: 'upsell',
      TimeToEnter: true,
      TradeTime: '15115'
    },
    {
      x: 16,
      y: 3564,
      dir: 'low',
      date: '',
      currentPrice: 3587,
      tradeStatus: 'not started',
      crudeTradePrice: 0,
      crudeTradeManagement: false,
      upcount: 0,
      downcount: 0,
      highest: 3588,
      lowest: 3486,
      trend: 'sideways',
      UPblackpoint: 3607,
      Lowblackpoint: 0,
      lowblackextreme: 0,
      upblackextreme: 3607,
      ShortTradeInitiated: true,
      retesthappen: true,
      bigDayTrade: 'short',
      bigDayTradePrice: 3588,
      sidecount: null
    },
    {
      x: 17,
      y: 3620,
      dir: 'up',
      date: '',
      currentPrice: 3594,
      tradeStatus: 'not started',
      crudeTradePrice: 0,
      crudeTradeManagement: false,
      upcount: 0,
      downcount: 0,
      highest: 3588,
      lowest: 3486,
      trend: 'sideways',
      UPblackpoint: 3620,
      Lowblackpoint: 0,
      lowblackextreme: 0,
      upblackextreme: 3620,
      ShortTradeInitiated: true,
      retesthappen: true,
      bigDayTrade: 'short',
      bigDayTradePrice: 3588
    },
    {
      x: 18,
      y: 3592,
      dir: 'low',
      date: '',
      currentPrice: 3612,
      tradeStatus: 'not started',
      crudeTradePrice: 0,
      crudeTradeManagement: false,
      upcount: 0,
      downcount: 0,
      highest: 3588,
      lowest: 3486,
      trend: 'sideways',
      UPblackpoint: 3620,
      Lowblackpoint: 0,
      lowblackextreme: 0,
      upblackextreme: 3620,
      ShortTradeInitiated: true,
      retesthappen: true,
      bigDayTrade: 'short',
      bigDayTradePrice: 3588
    },
    {
      x: 19,
      y: 3638,
      dir: 'up',
      date: '',
      currentPrice: 3618,
      tradeStatus: 'not started',
      crudeTradePrice: 0,
      crudeTradeManagement: false,
      upcount: 0,
      downcount: 0,
      highest: 3588,
      lowest: 3486,
      trend: 'sideways',
      UPblackpoint: 3638,
      Lowblackpoint: 0,
      lowblackextreme: 0,
      upblackextreme: 3638,
      ShortTradeInitiated: true,
      retesthappen: true,
      bigDayTrade: 'short',
      bigDayTradePrice: 3588
    }
  ],
  tickDataTest: [],
  plDataTest: [],
  plDataNifty: [],
  tickDataNifty: [],
  plDataNickle: [],
  tickDataNickle: [],
  tickDataJD: [],
  tickDataTCS: [],
  plDataTCS: []
}