{
  access: {},
  tickData: [
    {
      stop: 0,
      target: 0,
      shift: 0,
      open: 3606,
      low: 3595,
      high: 3606,
      close: 3601,
      tickType: 'red',
      tickLength: 11,
      date: '',
      detecting: false,
      tradeStatus: 'not started',
      trend: '',
      time: '8536',
      x: 1
    },
    {
      stop: 0,
      target: 0,
      shift: 0,
      open: 3597,
      low: 3593,
      high: 3597,
      close: 3595,
      tickType: 'red',
      tickLength: 4,
      date: '',
      detecting: false,
      tradeStatus: 'not started',
      y: 3593,
      time: '81536',
      x: 2,
      direction: 'down'
    },
    {
      stop: 0,
      target: 0,
      shift: 0,
      open: 3595,
      low: 3591,
      high: 3596,
      close: 3592,
      tickType: 'red',
      tickLength: 5,
      date: '',
      detecting: false,
      tradeStatus: 'not started',
      y: 3591,
      time: '82036',
      x: 3,
      direction: 'down'
    },
    {
      stop: 0,
      target: 0,
      shift: 0,
      open: 3591,
      low: 3584,
      high: 3592,
      close: 3585,
      tickType: 'red',
      tickLength: 8,
      date: '',
      detecting: false,
      tradeStatus: 'not started',
      y: 3584,
      time: '82536',
      x: 4,
      direction: 'down'
    },
    {
      stop: 0,
      target: 0,
      shift: 0,
      open: 3586,
      low: 3583,
      high: 3590,
      close: 3588,
      tickType: 'green',
      tickLength: 7,
      date: '',
      detecting: false,
      tradeStatus: 'not started',
      y: 3583,
      time: '83036',
      x: 5,
      direction: 'down'
    },
    {
      stop: 0,
      target: 0,
      shift: 0,
      open: 3588,
      low: 3579,
      high: 3590,
      close: 3580,
      tickType: 'red',
      tickLength: 11,
      date: '',
      detecting: false,
      tradeStatus: 'not started',
      y: 3579,
      time: '84036',
      x: 6,
      direction: 'down'
    },
    {
      stop: 0,
      target: 0,
      shift: 0,
      open: 3580,
      low: 3578,
      high: 3588,
      close: 3587,
      tickType: 'green',
      tickLength: 10,
      date: '',
      detecting: false,
      tradeStatus: 'not started',
      y: 3578,
      time: '84536',
      x: 7,
      direction: 'down'
    },
    {
      stop: 0,
      target: 0,
      shift: 0,
      open: 3587,
      low: 3586,
      high: 3590,
      close: 3589,
      tickType: 'green',
      tickLength: 4,
      date: '',
      detecting: false,
      tradeStatus: 'not started',
      y: 3590,
      time: '85036',
      x: 8,
      direction: 'up'
    },
    {
      stop: 0,
      target: 0,
      shift: 0,
      open: 3589,
      low: 3588,
      high: 3608,
      close: 3605,
      tickType: 'green',
      tickLength: 20,
      date: '',
      detecting: false,
      tradeStatus: 'not started',
      y: 3608,
      trend: 'upward',
      pivot: 3578,
      dir: 'low',
      currentPrice: 3605,
      time: '85536',
      x: 9,
      direction: 'up'
    },
    {
      stop: 0,
      target: 0,
      shift: 0,
      open: 3590,
      low: 3587,
      high: 3595,
      close: 3587,
      tickType: 'red',
      tickLength: 8,
      date: '',
      detecting: false,
      tradeStatus: 'not started',
      y: 3587,
      time: '93036',
      x: 10,
      direction: 'down'
    },
    {
      stop: 0,
      target: 0,
      shift: 0,
      open: 3587,
      low: 3586,
      high: 3589,
      close: 3587,
      tickType: 'doji',
      tickLength: 3,
      date: '',
      detecting: false,
      tradeStatus: 'not started',
      y: 3586,
      trend: 'downtrend',
      pivot: 3608,
      dir: 'up',
      currentPrice: 3587,
      time: '93536',
      x: 11,
      direction: 'down'
    },
    {
      stop: 0,
      target: 0,
      shift: 0,
      open: 3587,
      low: 3568,
      high: 3587,
      close: 3569,
      tickType: 'red',
      tickLength: 19,
      date: '',
      detecting: false,
      tradeStatus: 'not started',
      y: 3568,
      time: '94036',
      x: 12,
      direction: 'down'
    },
    {
      stop: 0,
      target: 0,
      shift: 0,
      open: 3569,
      low: 3567,
      high: 3573,
      close: 3570,
      tickType: 'green',
      tickLength: 6,
      date: '',
      detecting: false,
      tradeStatus: 'not started',
      y: 3567,
      time: '94536',
      x: 13,
      direction: 'down'
    },
    {
      stop: 0,
      target: 0,
      shift: 0,
      open: 3568,
      low: 3567,
      high: 3574,
      close: 3571,
      tickType: 'green',
      tickLength: 7,
      date: '',
      detecting: false,
      tradeStatus: 'not started',
      y: 3574,
      time: '95536',
      x: 14,
      direction: 'up'
    },
    {
      stop: 0,
      target: 0,
      shift: 0,
      open: 3571,
      low: 3569,
      high: 3575,
      close: 3575,
      tickType: 'green',
      tickLength: 6,
      date: '',
      detecting: false,
      tradeStatus: 'not started',
      y: 3575,
      trend: 'upward',
      pivot: 3567,
      dir: 'low',
      currentPrice: 3575,
      time: '10036',
      x: 15,
      direction: 'up'
    },
    {
      stop: 0,
      target: 0,
      shift: 0,
      open: 3558,
      low: 3546,
      high: 3562,
      close: 3546,
      tickType: 'red',
      tickLength: 16,
      date: '',
      detecting: false,
      tradeStatus: 'not started',
      y: 3546,
      time: '101036',
      x: 16,
      direction: 'down'
    },
    {
      stop: 0,
      target: 0,
      shift: 0,
      open: 3547,
      low: 3545,
      high: 3556,
      close: 3553,
      tickType: 'green',
      tickLength: 11,
      date: '',
      detecting: false,
      tradeStatus: 'not started',
      y: 3545,
      trend: 'downtrend',
      pivot: 3575,
      dir: 'up',
      currentPrice: 3553,
      time: '101536',
      x: 17,
      direction: 'down'
    },
    {
      stop: 0,
      target: 0,
      shift: 0,
      open: 3553,
      low: 3550,
      high: 3561,
      close: 3561,
      tickType: 'green',
      tickLength: 11,
      date: '',
      detecting: false,
      tradeStatus: 'not started',
      y: 3561,
      time: '102036',
      x: 18,
      direction: 'up'
    },
    {
      stop: 0,
      target: 0,
      shift: 0,
      open: 3561,
      low: 3553,
      high: 3563,
      close: 3554,
      tickType: 'red',
      tickLength: 10,
      date: '',
      detecting: false,
      tradeStatus: 'not started',
      y: 3563,
      trend: 'upward',
      pivot: 3545,
      dir: 'low',
      currentPrice: 3554,
      time: '102536',
      x: 19,
      direction: 'up'
    },
    {
      stop: 0,
      target: 0,
      shift: 0,
      open: 3553,
      low: 3553,
      high: 3564,
      close: 3560,
      tickType: 'green',
      tickLength: 11,
      date: '',
      detecting: false,
      tradeStatus: 'not started',
      y: 3564,
      time: '105036',
      x: 20,
      direction: 'up'
    },
    {
      stop: 0,
      target: 0,
      shift: 0,
      open: 3558,
      low: 3552,
      high: 3558,
      close: 3553,
      tickType: 'red',
      tickLength: 6,
      date: '',
      detecting: false,
      tradeStatus: 'not started',
      y: 3552,
      time: '11036',
      x: 21,
      direction: 'down'
    },
    {
      stop: 0,
      target: 0,
      shift: 0,
      open: 3554,
      low: 3543,
      high: 3555,
      close: 3551,
      tickType: 'red',
      tickLength: 12,
      date: '',
      detecting: false,
      tradeStatus: 'not started',
      y: 3543,
      trend: 'downtrend',
      pivot: 3564,
      dir: 'up',
      currentPrice: 3551,
      time: '11536',
      x: 22,
      direction: 'down'
    },
    {
      stop: 0,
      target: 0,
      shift: 0,
      open: 3546,
      low: 3542,
      high: 3548,
      close: 3542,
      tickType: 'red',
      tickLength: 6,
      date: '',
      detecting: false,
      tradeStatus: 'not started',
      y: 3542,
      time: '112536',
      x: 23,
      direction: 'down'
    },
    {
      stop: 0,
      target: 0,
      shift: 0,
      open: 3548,
      low: 3536,
      high: 3548,
      close: 3543,
      tickType: 'red',
      tickLength: 12,
      date: '',
      detecting: false,
      tradeStatus: 'not started',
      y: 3536,
      time: '114036',
      x: 24,
      direction: 'down'
    },
    {
      stop: 0,
      target: 0,
      shift: 0,
      open: 3552,
      low: 3531,
      high: 3553,
      close: 3536,
      tickType: 'red',
      tickLength: 22,
      date: '',
      detecting: false,
      tradeStatus: 'not started',
      y: 3531,
      time: '115536',
      x: 25,
      direction: 'down'
    },
    {
      stop: 0,
      target: 0,
      shift: 0,
      open: 3539,
      low: 3525,
      high: 3548,
      close: 3547,
      tickType: 'green',
      tickLength: 23,
      date: '',
      detecting: false,
      tradeStatus: 'not started',
      y: 3525,
      time: '123036',
      x: 26,
      direction: 'down'
    },
    {
      stop: 0,
      target: 0,
      shift: 0,
      open: 3546,
      low: 3545,
      high: 3558,
      close: 3553,
      tickType: 'green',
      tickLength: 13,
      date: '',
      detecting: false,
      tradeStatus: 'not started',
      y: 3558,
      time: '123536',
      x: 27,
      direction: 'up'
    },
    {
      stop: 0,
      target: 0,
      shift: 0,
      open: 3552,
      low: 3544,
      high: 3563,
      close: 3545,
      tickType: 'red',
      tickLength: 19,
      date: '',
      detecting: false,
      tradeStatus: 'not started',
      y: 3563,
      trend: 'upward',
      pivot: 3525,
      dir: 'low',
      currentPrice: 3545,
      time: '13536',
      x: 28,
      direction: 'up'
    },
    {
      stop: 0,
      target: 0,
      shift: 0,
      open: 3545,
      low: 3532,
      high: 3547,
      close: 3538,
      tickType: 'red',
      tickLength: 15,
      date: '',
      detecting: false,
      tradeStatus: 'not started',
      y: 3532,
      time: '131036',
      x: 29,
      direction: 'down'
    },
    {
      stop: 0,
      target: 0,
      shift: 0,
      open: 3546,
      low: 3506,
      high: 3546,
      close: 3513,
      tickType: 'red',
      tickLength: 40,
      date: '',
      detecting: false,
      tradeStatus: 'not started',
      y: 3506,
      trend: 'downtrend',
      pivot: 3563,
      dir: 'up',
      currentPrice: 3513,
      time: '142036',
      x: 30,
      direction: 'down'
    },
    {
      stop: 0,
      target: 0,
      shift: 0,
      open: 3512,
      low: 3503,
      high: 3516,
      close: 3503,
      tickType: 'red',
      tickLength: 13,
      date: '',
      detecting: false,
      tradeStatus: 'not started',
      y: 3503,
      time: '142536',
      x: 31,
      direction: 'down'
    },
    {
      stop: 0,
      target: 0,
      shift: 0,
      open: 3514,
      low: 3494,
      high: 3517,
      close: 3501,
      tickType: 'red',
      tickLength: 23,
      date: '',
      detecting: false,
      tradeStatus: 'not started',
      y: 3494,
      time: '144536',
      x: 32,
      direction: 'down'
    },
    {
      stop: 0,
      target: 0,
      shift: 0,
      open: 3500,
      low: 3482,
      high: 3503,
      close: 3486,
      tickType: 'red',
      tickLength: 21,
      date: '',
      detecting: false,
      tradeStatus: 'not started',
      y: 3482,
      time: '145036',
      x: 33,
      direction: 'down'
    },
    {
      stop: 0,
      target: 0,
      shift: 0,
      open: 3491,
      low: 3487,
      high: 3511,
      close: 3504,
      tickType: 'green',
      tickLength: 24,
      date: '',
      detecting: false,
      tradeStatus: 'not started',
      y: 3511,
      time: '15536',
      x: 34,
      direction: 'up'
    },
    {
      stop: 0,
      target: 0,
      shift: 0,
      open: 3504,
      low: 3501,
      high: 3512,
      close: 3509,
      tickType: 'green',
      tickLength: 11,
      date: '',
      detecting: false,
      tradeStatus: 'not started',
      y: 3512,
      trend: 'upward',
      pivot: 3482,
      dir: 'low',
      currentPrice: 3509,
      time: '151036',
      x: 35,
      direction: 'up'
    },
    {
      stop: 0,
      target: 0,
      shift: 0,
      open: 3509,
      low: 3502,
      high: 3514,
      close: 3509,
      tickType: 'doji',
      tickLength: 12,
      date: '',
      detecting: false,
      tradeStatus: 'not started',
      y: 3514,
      time: '151536',
      x: 36,
      direction: 'up'
    },
    {
      stop: 0,
      target: 0,
      shift: 0,
      open: 3506,
      low: 3505,
      high: 3518,
      close: 3516,
      tickType: 'green',
      tickLength: 13,
      date: '',
      detecting: false,
      tradeStatus: 'not started',
      y: 3518,
      time: '152536',
      x: 37,
      direction: 'up'
    },
    {
      stop: 0,
      target: 0,
      shift: 0,
      open: 3516,
      low: 3510,
      high: 3520,
      close: 3511,
      tickType: 'red',
      tickLength: 10,
      date: '',
      detecting: false,
      tradeStatus: 'not started',
      y: 3520,
      time: '153036',
      x: 38,
      direction: 'up'
    },
    {
      stop: 0,
      target: 0,
      shift: 0,
      open: 3511,
      low: 3506,
      high: 3529,
      close: 3523,
      tickType: 'green',
      tickLength: 23,
      date: '',
      detecting: false,
      tradeStatus: 'not started',
      y: 3529,
      time: '153536',
      x: 39,
      direction: 'up'
    },
    {
      stop: 0,
      target: 0,
      shift: 0,
      open: 3523,
      low: 3520,
      high: 3535,
      close: 3534,
      tickType: 'green',
      tickLength: 15,
      date: '',
      detecting: false,
      tradeStatus: 'not started',
      y: 3535,
      time: '154036',
      x: 40,
      direction: 'up'
    },
    {
      stop: 0,
      target: 0,
      shift: 0,
      open: 3534,
      low: 3531,
      high: 3540,
      close: 3539,
      tickType: 'green',
      tickLength: 9,
      date: '',
      detecting: false,
      tradeStatus: 'not started',
      y: 3540,
      time: '154536',
      x: 41,
      direction: 'up'
    },
    {
      stop: 0,
      target: 0,
      shift: 0,
      open: 3540,
      low: 3535,
      high: 3549,
      close: 3540,
      tickType: 'doji',
      tickLength: 14,
      date: '',
      detecting: false,
      tradeStatus: 'not started',
      y: 3549,
      time: '155036',
      x: 42,
      direction: 'up'
    },
    {
      stop: 0,
      target: 0,
      shift: 0,
      open: 3540,
      low: 3531,
      high: 3540,
      close: 3532,
      tickType: 'red',
      tickLength: 9,
      date: '',
      detecting: false,
      tradeStatus: 'not started',
      y: 3531,
      time: '155536',
      x: 43,
      direction: 'down'
    },
    {
      stop: 0,
      target: 0,
      shift: 0,
      open: 3532,
      low: 3512,
      high: 3532,
      close: 3519,
      tickType: 'red',
      tickLength: 20,
      date: '',
      detecting: false,
      tradeStatus: 'not started',
      y: 3512,
      trend: 'downtrend',
      pivot: 3549,
      dir: 'up',
      currentPrice: 3519,
      time: '16036',
      x: 44,
      direction: 'down'
    },
    {
      stop: 0,
      target: 0,
      shift: 0,
      open: 3520,
      low: 3517,
      high: 3534,
      close: 3532,
      tickType: 'green',
      tickLength: 17,
      date: '',
      detecting: false,
      tradeStatus: 'not started',
      y: 3534,
      time: '16536',
      x: 45,
      direction: 'up'
    },
    {
      stop: 0,
      target: 0,
      shift: 0,
      open: 3532,
      low: 3526,
      high: 3539,
      close: 3535,
      tickType: 'green',
      tickLength: 13,
      date: '',
      detecting: false,
      tradeStatus: 'not started',
      y: 3539,
      trend: 'upward',
      pivot: 3512,
      dir: 'low',
      currentPrice: 3535,
      time: '161036',
      x: 46,
      direction: 'up'
    },
    {
      stop: 0,
      target: 0,
      shift: 0,
      open: 3536,
      low: 3534,
      high: 3543,
      close: 3536,
      tickType: 'doji',
      tickLength: 9,
      date: '',
      detecting: false,
      tradeStatus: 'not started',
      y: 3543,
      time: '161536',
      x: 47,
      direction: 'up'
    },
    {
      stop: 0,
      target: 0,
      shift: 0,
      open: 3536,
      low: 3530,
      high: 3545,
      close: 3542,
      tickType: 'green',
      tickLength: 15,
      date: '',
      detecting: false,
      tradeStatus: 'not started',
      y: 3545,
      time: '162036',
      x: 48,
      direction: 'up'
    },
    {
      stop: 0,
      target: 0,
      shift: 0,
      open: 3543,
      low: 3521,
      high: 3547,
      close: 3522,
      tickType: 'red',
      tickLength: 26,
      date: '',
      detecting: false,
      tradeStatus: 'not started',
      y: 3547,
      time: '162536',
      x: 49,
      direction: 'up'
    },
    {
      stop: 0,
      target: 0,
      shift: 0,
      open: 3532,
      low: 3532,
      high: 3561,
      close: 3551,
      tickType: 'green',
      tickLength: 29,
      date: '',
      detecting: false,
      tradeStatus: 'not started',
      y: 3561,
      time: '163536',
      x: 50,
      direction: 'up'
    },
    {
      stop: 0,
      target: 0,
      shift: 0,
      open: 3551,
      low: 3551,
      high: 3564,
      close: 3559,
      tickType: 'green',
      tickLength: 13,
      date: '',
      detecting: false,
      tradeStatus: 'not started',
      y: 3564,
      time: '164036',
      x: 51,
      direction: 'up'
    },
    {
      stop: 0,
      target: 0,
      shift: 0,
      open: 3559,
      low: 3558,
      high: 3572,
      close: 3569,
      tickType: 'green',
      tickLength: 14,
      date: '',
      detecting: false,
      tradeStatus: 'not started',
      y: 3572,
      time: '164536',
      x: 52,
      direction: 'up'
    },
    {
      stop: 0,
      target: 0,
      shift: 0,
      open: 3570,
      low: 3566,
      high: 3582,
      close: 3580,
      tickType: 'green',
      tickLength: 16,
      date: '',
      detecting: false,
      tradeStatus: 'not started',
      y: 3582,
      time: '165036',
      x: 53,
      direction: 'up'
    },
    {
      stop: 0,
      target: 0,
      shift: 0,
      open: 3581,
      low: 3569,
      high: 3597,
      close: 3597,
      tickType: 'green',
      tickLength: 28,
      date: '',
      detecting: false,
      tradeStatus: 'not started',
      y: 3597,
      time: '165536',
      x: 54,
      direction: 'up'
    },
    {
      stop: 0,
      target: 0,
      shift: 0,
      open: 3597,
      low: 3594,
      high: 3606,
      close: 3600,
      tickType: 'green',
      tickLength: 12,
      date: '',
      detecting: false,
      tradeStatus: 'not started',
      y: 3606,
      time: '17036',
      x: 55,
      direction: 'up'
    },
    {
      stop: 0,
      target: 0,
      shift: 0,
      open: 3599,
      low: 3590,
      high: 3612,
      close: 3594,
      tickType: 'red',
      tickLength: 22,
      date: '',
      detecting: false,
      tradeStatus: 'not started',
      y: 3612,
      time: '17536',
      x: 56,
      direction: 'up'
    },
    {
      stop: 0,
      target: 0,
      shift: 0,
      open: 3594,
      low: 3582,
      high: 3600,
      close: 3587,
      tickType: 'red',
      tickLength: 18,
      date: '',
      detecting: false,
      tradeStatus: 'not started',
      y: 3582,
      time: '171036',
      x: 57,
      direction: 'down'
    },
    {
      stop: 0,
      target: 0,
      shift: 0,
      open: 3587,
      low: 3574,
      high: 3589,
      close: 3581,
      tickType: 'red',
      tickLength: 15,
      date: '',
      detecting: false,
      tradeStatus: 'not started',
      y: 3574,
      trend: 'downtrend',
      pivot: 3612,
      dir: 'up',
      currentPrice: 3581,
      time: '174036',
      x: 58,
      direction: 'down'
    },
    {
      stop: 0,
      target: 0,
      shift: 0,
      open: 3577,
      low: 3573,
      high: 3588,
      close: 3583,
      tickType: 'green',
      tickLength: 15,
      date: '',
      detecting: false,
      tradeStatus: 'not started',
      y: 3573,
      time: '175536',
      x: 59,
      direction: 'down'
    },
    {
      stop: 0,
      target: 0,
      shift: 0,
      open: 3581,
      low: 3572,
      high: 3585,
      close: 3573,
      tickType: 'red',
      tickLength: 13,
      date: '',
      detecting: false,
      tradeStatus: 'not started',
      y: 3572,
      time: '18536',
      x: 60,
      direction: 'down'
    },
    {
      stop: 0,
      target: 0,
      shift: 0,
      open: 3573,
      low: 3563,
      high: 3573,
      close: 3571,
      tickType: 'red',
      tickLength: 10,
      date: '',
      detecting: false,
      tradeStatus: 'not started',
      y: 3563,
      time: '181036',
      x: 61,
      direction: 'down'
    },
    {
      stop: 0,
      target: 0,
      shift: 0,
      open: 3573,
      low: 3565,
      high: 3574,
      close: 3572,
      tickType: 'red',
      tickLength: 9,
      date: '',
      detecting: false,
      tradeStatus: 'not started',
      y: 3574,
      time: '181536',
      x: 62,
      direction: 'up'
    },
    {
      stop: 0,
      target: 0,
      shift: 0,
      open: 3572,
      low: 3571,
      high: 3581,
      close: 3581,
      tickType: 'green',
      tickLength: 10,
      date: '',
      detecting: false,
      tradeStatus: 'not started',
      y: 3581,
      trend: 'upward',
      pivot: 3563,
      dir: 'low',
      currentPrice: 3581,
      time: '182036',
      x: 63,
      direction: 'up'
    },
    {
      stop: 0,
      target: 0,
      shift: 0,
      open: 3581,
      low: 3580,
      high: 3592,
      close: 3587,
      tickType: 'green',
      tickLength: 12,
      date: '',
      detecting: false,
      tradeStatus: 'not started',
      y: 3592,
      time: '182536',
      x: 64,
      direction: 'up'
    },
    {
      stop: 0,
      target: 0,
      shift: 0,
      tickLength: null,
      date: '',
      detecting: false,
      tradeStatus: 'not started',
      time: '183036',
      x: 65,
      direction: ''
    },
    {
      stop: 0,
      target: 0,
      shift: 0,
      open: 3587,
      low: 3587,
      high: 3587,
      close: 3587,
      tickType: 'doji',
      tickLength: 0,
      date: '',
      detecting: false,
      tradeStatus: 'not started',
      y: 3587,
      time: '183536',
      x: 66,
      direction: ''
    },
    {
      stop: 0,
      target: 0,
      shift: 0,
      tickLength: null,
      date: '',
      detecting: false,
      tradeStatus: 'not started',
      time: '184036',
      x: 67,
      direction: ''
    },
    {
      stop: 0,
      target: 0,
      shift: 0,
      open: 3587,
      low: 3587,
      high: 3587,
      close: 3587,
      tickType: 'doji',
      tickLength: 0,
      date: '',
      detecting: false,
      tradeStatus: 'not started',
      y: 3587,
      time: '11536',
      x: 68,
      direction: ''
    },
    {
      stop: 0,
      target: 0,
      shift: 0,
      tickLength: null,
      date: '',
      detecting: false,
      tradeStatus: 'not started',
      time: '12036',
      x: 69,
      direction: ''
    },
    {
      stop: 0,
      target: 0,
      shift: 0,
      open: 2600,
      low: 2471,
      high: 4000,
      close: 2600,
      tickType: 'doji',
      tickLength: 1529,
      date: '',
      detecting: false,
      tradeStatus: 'not started',
      y: 2600,
      time: '5529',
      x: 70,
      direction: ''
    },
    {
      stop: 0,
      target: 0,
      shift: 0,
      open: 2600,
      low: 2470,
      high: 4700,
      close: 3950,
      tickType: 'green',
      tickLength: 2230,
      date: '',
      detecting: false,
      tradeStatus: 'not started',
      y: 4700,
      time: '51529',
      x: 71,
      direction: 'up'
    },
    {
      stop: 0,
      target: 0,
      shift: 0,
      open: 4000,
      low: 3800,
      high: 4794,
      close: 3820,
      tickType: 'red',
      tickLength: 994,
      date: '',
      detecting: false,
      tradeStatus: 'not started',
      y: 4794,
      trend: 'upward',
      pivot: 2471,
      dir: 'low',
      currentPrice: 3820,
      time: '52029',
      x: 72,
      direction: 'up'
    },
    {
      stop: 0,
      target: 0,
      shift: 0,
      open: 3902,
      low: 3704,
      high: 4900,
      close: 4800,
      tickType: 'green',
      tickLength: 1196,
      date: '',
      detecting: false,
      tradeStatus: 'not started',
      y: 4900,
      time: '7529',
      x: 73,
      direction: 'up'
    },
    {
      stop: 0,
      target: 0,
      shift: 0,
      open: 4600,
      low: 4600,
      high: 4903,
      close: 4903,
      tickType: 'green',
      tickLength: 303,
      date: '',
      detecting: false,
      tradeStatus: 'not started',
      y: 4903,
      time: '71529',
      x: 74,
      direction: 'up'
    },
    {
      stop: 0,
      target: 0,
      shift: 0,
      open: 4800,
      low: 3703,
      high: 4900,
      close: 4800,
      tickType: 'doji',
      tickLength: 1197,
      date: '',
      detecting: false,
      tradeStatus: 'not started',
      y: 3703,
      time: '72529',
      x: 75,
      direction: 'down'
    }
  ],
  plData: [
    {
      x: 0,
      y: 3606
    },
    {
      x: 1,
      y: 3578,
      dir: 'low',
      date: '',
      currentPrice: 3605,
      tradeStatus: 'not started',
      crudeTradePrice: 0,
      crudeTradeManagement: false,
      highest: 3606,
      lowest: 3578,
      sidecount: 0
    },
    {
      x: 2,
      y: 3608,
      dir: 'up',
      date: '',
      currentPrice: 3587,
      tradeStatus: 'not started',
      crudeTradePrice: 0,
      crudeTradeManagement: false,
      highest: 3608,
      lowest: 3578,
      sidecount: 0
    },
    {
      x: 3,
      y: 3567,
      dir: 'low',
      date: '',
      currentPrice: 3575,
      tradeStatus: 'not started',
      crudeTradePrice: 0,
      crudeTradeManagement: false,
      highest: 3608,
      lowest: 3578,
      sidecount: 1,
      downcount: 1,
      lowblackextreme: 3567,
      lowblackextremeindex: 3
    },
    {
      x: 4,
      y: 3575,
      dir: 'up',
      date: '',
      currentPrice: 3553,
      tradeStatus: 'not started',
      crudeTradePrice: 0,
      crudeTradeManagement: false,
      downcount: 0,
      highest: 3608,
      lowest: 3567,
      lowblackextreme: 0,
      lowblackextremeindex: 3,
      trend: 'downtrend',
      upcount: 0,
      sidecount: 1,
      upblackextreme: 0,
      UPblackpoint: 0,
      Lowblackpoint: 0
    },
    {
      x: 5,
      y: 3545,
      dir: 'low',
      date: '',
      currentPrice: 3554,
      tradeStatus: 'not started',
      crudeTradePrice: 0,
      crudeTradeManagement: false,
      upcount: 0,
      downcount: 0,
      highest: 3575,
      lowest: 3545,
      trend: 'downtrend',
      UPblackpoint: 0,
      Lowblackpoint: 0,
      lowblackextreme: 0,
      upblackextreme: 0,
      lowblackextremeindex: 3,
      sidecount: 0
    },
    {
      x: 6,
      y: 3564,
      dir: 'up',
      date: '',
      currentPrice: 3551,
      tradeStatus: 'not started',
      crudeTradePrice: 0,
      crudeTradeManagement: false,
      upcount: 0,
      downcount: 0,
      highest: 3575,
      lowest: 3545,
      trend: 'downtrend',
      UPblackpoint: 0,
      Lowblackpoint: 0,
      lowblackextreme: 0,
      upblackextreme: 0,
      lowblackextremeindex: 3,
      sidecount: 1
    },
    {
      x: 7,
      y: 3525,
      dir: 'low',
      date: '',
      currentPrice: 3545,
      tradeStatus: 'not started',
      crudeTradePrice: 0,
      crudeTradeManagement: false,
      upcount: 0,
      downcount: 0,
      highest: 3564,
      lowest: 3525,
      trend: 'downtrend',
      UPblackpoint: 0,
      Lowblackpoint: 0,
      lowblackextreme: 0,
      upblackextreme: 0,
      lowblackextremeindex: 3,
      sidecount: 0
    },
    {
      x: 8,
      y: 3563,
      dir: 'up',
      date: '',
      currentPrice: 3513,
      tradeStatus: 'not started',
      crudeTradePrice: 0,
      crudeTradeManagement: false,
      upcount: 0,
      downcount: 0,
      highest: 3564,
      lowest: 3525,
      trend: 'downtrend',
      UPblackpoint: 0,
      Lowblackpoint: 0,
      lowblackextreme: 0,
      upblackextreme: 0,
      lowblackextremeindex: 3,
      sidecount: 1
    },
    {
      x: 9,
      y: 3482,
      dir: 'low',
      date: '',
      currentPrice: 3509,
      tradeStatus: 'not started',
      crudeTradePrice: 0,
      crudeTradeManagement: false,
      upcount: 0,
      downcount: 0,
      highest: 3563,
      lowest: 3482,
      trend: 'downtrend',
      UPblackpoint: 0,
      Lowblackpoint: 0,
      lowblackextreme: 0,
      upblackextreme: 0,
      lowblackextremeindex: 3,
      sidecount: 0
    },
    {
      x: 10,
      y: 3549,
      dir: 'up',
      date: '',
      currentPrice: 3519,
      tradeStatus: 'not started',
      crudeTradePrice: 0,
      crudeTradeManagement: false,
      upcount: 0,
      downcount: 0,
      highest: 3563,
      lowest: 3482,
      trend: 'downtrend',
      UPblackpoint: 0,
      Lowblackpoint: 0,
      lowblackextreme: 0,
      upblackextreme: 0,
      lowblackextremeindex: 3,
      sidecount: 1
    },
    {
      x: 11,
      y: 3512,
      dir: 'low',
      date: '',
      currentPrice: 3535,
      tradeStatus: 'not started',
      crudeTradePrice: 0,
      crudeTradeManagement: false,
      upcount: 0,
      downcount: 0,
      highest: 3563,
      lowest: 3482,
      trend: 'downtrend',
      UPblackpoint: 0,
      Lowblackpoint: 0,
      lowblackextreme: 0,
      upblackextreme: 0,
      lowblackextremeindex: 3,
      sidecount: 2
    },
    {
      x: 12,
      y: 3612,
      dir: 'up',
      date: '',
      currentPrice: 3581,
      tradeStatus: 'not started',
      crudeTradePrice: 0,
      crudeTradeManagement: false,
      upcount: 0,
      downcount: 0,
      highest: 3612,
      lowest: 3512,
      trend: 'downtrend',
      UPblackpoint: 0,
      Lowblackpoint: 0,
      lowblackextreme: 0,
      upblackextreme: 0,
      lowblackextremeindex: 3,
      bigDayTrade: 'short',
      bigDayTradePrice: 3612,
      sidecount: 0
    },
    {
      x: 13,
      y: 3563,
      dir: 'low',
      date: '',
      currentPrice: 3581,
      tradeStatus: 'not started',
      crudeTradePrice: 0,
      crudeTradeManagement: false,
      upcount: 0,
      downcount: 0,
      highest: 3612,
      lowest: 3512,
      trend: 'downtrend',
      UPblackpoint: 0,
      Lowblackpoint: 0,
      lowblackextreme: 0,
      upblackextreme: 0,
      lowblackextremeindex: 3,
      bigDayTrade: 'short',
      bigDayTradePrice: 3612,
      sidecount: 1
    },
    {
      x: 14,
      y: 2471,
      dir: 'low',
      date: '',
      currentPrice: 3820,
      tradeStatus: 'not started',
      crudeTradePrice: 0,
      crudeTradeManagement: false,
      upcount: 0,
      downcount: 0,
      highest: 3563,
      lowest: 2471,
      trend: 'downtrend',
      UPblackpoint: 0,
      Lowblackpoint: 0,
      lowblackextreme: 0,
      upblackextreme: 0,
      lowblackextremeindex: 3,
      bigDayTrade: 'long',
      bigDayTradePrice: 2471,
      sidecount: 0
    }
  ],
  tickDataTest: [],
  plDataTest: [],
  plDataNifty: [],
  tickDataNifty: [],
  plDataNickle: [],
  tickDataNickle: [],
  tickDataJD: [],
  tickDataTCS: [],
  plDataTCS: []
}